- name: Add APT key
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present

- name: super-ugly hack to allow unauthenticated packages to install
  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99temp owner=root group=root mode=0644

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
- name: remove hack that allows unauthenticated packages to install
  file: path=/etc/apt/apt.conf.d/99temp state=absents
